version: "3.9"
services:
  postgres:
    image: postgres:15.3
    environment:
      - POSTGRES_USER=staff
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=simplebank
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_SOURCE: "postgresql://staff:secret@postgres:5432/simplebank?sslmode=disable"
    depends_on:
      - postgres
    entrypoint:
      [
        "/app/wait-for.sh",
        "postgres:5432",
        "--",
        "/app/start.sh"
      ]
    command: [ "/app/main" ]